//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.13 at 12:35:57 PM CAT 
//


package com.loanscompany.lam.utility.enums;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponseCodes.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponseCodes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="Z"/&gt;
 *     &lt;enumeration value="Y"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "ResponseCodes", namespace = "http://zieto.co.za/claim/zmf/datatypes")
@XmlEnum
public enum ResponseCodes {


    /**
     * Approved
     */
    A,

    /**
     * Rejected
     */
    R,

    /**
     * Partial
     */
    P,

    /**
     * Successful Reversal
     */
    Z,

    /**
     * Unsuccessful Reversal
     */
    Y,

    /**
     * Accepted claim with zero values paid.
     */
    O,

    /**
     * Pending claim.
     */
    D;

    public String value() {
        return name();
    }

    public static ResponseCodes fromValue(String v) {
        return valueOf(v);
    }

}
